name: Dogfood

on: pull_request

permissions:
  contents: read

jobs:
  github-actions-example:
    name: GitHub Actions Example
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code.
        uses: actions/checkout@v7
      - name: Check Rust whitespace consistency.
        uses: docker://ghcr.io/developerc286/consistent_whitespace:v0.7.3
        with:
          args: src/ Cargo.toml
      - name: Check Python whitespace consistency.
        uses: docker://ghcr.io/developerc286/consistent_whitespace:v0.7.3
        with:
          args: end-to-end-tests/features/
      - name: Check shell whitespace consistency.
        uses: docker://ghcr.io/developerc286/consistent_whitespace:v0.7.3
        with:
          args: ci/
      - name: Check Dockerfile whitespace consistency.
        uses: docker://ghcr.io/developerc286/consistent_whitespace:v0.7.3
        with:
          args: Dockerfile
