name: Dogfood

on: pull_request

permissions:
  contents: read

jobs:
  github-actions-example:
    name: GitHub Actions Example
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code.
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Check whitespace consistency.
        uses: docker://ghcr.io/developerc286/consistent_whitespace:v0.6.0@sha256:b254ce59fc89cf0369aba7431da02393c04bd1fe4ede2bfdc8bef55cdafb0008
        with:
          args: .
